# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('security', '2120001_initial'),
        ('via', '2120001_initial'),
        ('authccenter', '2120001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbmconfigapp', '2120001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresultgrid',
            name='dbMotion_patient_attribute_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, blank=True, to='via.InitiateMappings', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='searchresultgrid',
            name='pv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVPatientSearchPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='pvreportingpage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='pvreportingpage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='pvpatientsearchpage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='pvpatientsearchpage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='pvpatientnamedisplay',
            name='pv_parent_patient_display',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='pvpatientdisplaypage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='pvpatientdisplaypage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='pvmeasurementpage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='pvmeasurementpage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='pvclinicaldomainpage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='pvclinicaldomainpage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='pvclinicalcodedisplaypage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='pvclinicalcodedisplaypage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='pvccdadisplaypage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='pvccdadisplaypage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='pvcategoriesproperties',
            name='parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVClinicalDomainPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ppolgeneral',
            name='parent_empi_id',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='via.EmpiPpolGeneralPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='plreportingpage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='plreportingpage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='plpatientdisplaypage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='plpatientdisplaypage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='plgeneralpage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='plgeneralpage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='plclinicalcodedisplaypage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='plclinicalcodedisplaypage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='patientviewpage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='patientviewpage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='patientviewgeneraldefinitions',
            name='default_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, default=b'', to='security.ADProviders', blank=True, help_text=b'This configuration is to define the default active directory domain in Login page of standalone mode.<br/>The Domain must be added first to the list in Active directory domains.<br/><i>Default: N/A</i>', null=True, verbose_name=b'Default Active Directory Domain'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='patientviewgeneraldefinitions',
            name='patient_view_page',
            field=models.ForeignKey(on_delete=models.CASCADE, default=1, to='dbmconfigapp.PatientViewPage'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='patientviewdefaultlandingpage',
            name='patient_view_page',
            field=models.ForeignKey(on_delete=models.CASCADE, default=1, to='dbmconfigapp.PatientViewPage'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='patientslistviews',
            name='patient_view_page',
            field=models.ForeignKey(on_delete=models.CASCADE, default=1, to='dbmconfigapp.PatientViewPage'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='patientsearchtooltip',
            name='clinical_domain',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=14, to='dbmconfigapp.ClinicalDomain', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='patientsearchtooltip',
            name='pv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVPatientSearchPage', null=True),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='patientsearchtooltip',
            unique_together=set([('culture', 'message')]),
        ),
        migrations.AddField(
            model_name='patientsearchdisplayoptions',
            name='patient_search_page',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=14, to='dbmconfigapp.PatientSearchPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='patientsearchdisplayoptions',
            name='pv_patient_search_page',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, to='dbmconfigapp.PVPatientSearchPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='patientsearchdefaultsearch',
            name='patient_search_page',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=14, to='dbmconfigapp.PatientSearchPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='patientdetailssectionordering',
            name='pl_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, to='dbmconfigapp.PlPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='patientdetailssectionordering',
            name='pv_parent_patient_display',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='participantlistmodel',
            name='institude_name',
            field=models.ForeignKey(on_delete=models.CASCADE, default=1, to='dbmconfigapp.ParticipantListBasedPAAModel'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='participantlistbasedpaamodel',
            name='page',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.CarequalityIntegrationSettingsPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='participantbaselinelistmodel',
            name='page',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.CarequalityIntegrationSettingsPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='operationalmanagerpage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='operationalmanagerpage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='myhrorganizationsentity',
            name='page',
            field=models.ForeignKey(on_delete=models.CASCADE, default=1, to='dbmconfigapp.MyHRConnectivityPage'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='myhrconnectivitypage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='myhrconnectivitypage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='myhrconnectivityentity',
            name='page',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.MyHRConnectivityPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='modeldescriptor',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='loginshistory',
            name='ccenter_user',
            field=models.ForeignKey(on_delete=models.SET_NULL, to='authccenter.CCenterUser', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='loginshistory',
            name='user',
            field=models.ForeignKey(on_delete=models.SET_NULL, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='launchergeneralproperties',
            name='default_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, default=None, to='dbmconfigapp.AgentppHostedApp', blank=True, help_text=b"Defines the default application to be launched via the Application Launcher's middle button.<br/><i>Default: Patient View (if the application is enabled).</i>", null=True, verbose_name=b'Default Application'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='launchergeneralproperties',
            name='page',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.AgentppHostedAppPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='labchartdisplayoptions',
            name='parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=16, to='dbmconfigapp.ClinicalDomainLaboratory', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='imagingpacsparameter',
            name='imaging_pacs',
            field=models.ForeignKey(on_delete=models.CASCADE, to='dbmconfigapp.ImagingPacs'),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='imagingpacsparameter',
            unique_together=set([('name', 'imaging_pacs')]),
        ),
        migrations.AddField(
            model_name='imagingpacsdisclaimer',
            name='pv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVClinicalDomainPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='imagingpacs',
            name='clinical_domain',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=17, editable=False, to='dbmconfigapp.ClinicalDomain', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='imagingpacs',
            name='pv_clinical_domain_page',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVClinicalDomainPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='externalapplicationparameter',
            name='external_application',
            field=models.ForeignKey(on_delete=models.CASCADE, to='dbmconfigapp.ExternalApplication'),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='externalapplicationparameter',
            unique_together=set([('name', 'external_application')]),
        ),
        migrations.AddField(
            model_name='externalapplication',
            name='cv_general_page',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.ClinicalViewerGeneralPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='encounterdiagnosisrelationship',
            name='pl_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PlGeneralPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='encounterdiagnosisrelationship',
            name='pv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVClinicalDomainPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='emergencydeclarationtext',
            name='patient_search_page',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=14, to='dbmconfigapp.PatientSearchPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='emergencydeclarationtext',
            name='pv_emg_declaration_patient_search',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVPatientSearchPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='emergencydeclarationreasons',
            name='clinical_domain',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=14, to='dbmconfigapp.ClinicalDomain', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='emergencydeclarationreasons',
            name='pv_patient_search',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVPatientSearchPage', null=True),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='emergencydeclarationreasons',
            unique_together=set([('culture', 'message')]),
        ),
        migrations.AddField(
            model_name='ehragenttooltips',
            name='category',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.EHRAgentCategoriesProperties', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ehragentsemanticgroup',
            name='pv_measurement',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, to='dbmconfigapp.PVMeasurementPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ehragentsemanticdelta',
            name='pv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVClinicalDomainPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ehragentmeasurementproperties',
            name='semantic_group',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, to='dbmconfigapp.EHRAgentSemanticGroup', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ehragentgeneral',
            name='pv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVClinicalDomainPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ehragentcvcommonclinicaldomainsproperties',
            name='cv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, to='dbmconfigapp.ClinicalDomain', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ehragentclinicaldomainsproperties',
            name='pv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVClinicalDomainPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ehragentcategoriesproperties',
            name='topic',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, to='dbmconfigapp.EHRAgentCategoriesTopic', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ehragentblinks',
            name='pv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVClinicalDomainPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ehragentbaseurl',
            name='agenthub_general_page',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.AgentHubGeneralPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='documentsearchlivefeedsproperties',
            name='parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.DocumentSearchLiveFeeds', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='documentsearchlivefeeds',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='documentsearchlivefeeds',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='documentsearchgeneralproperties',
            name='parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.DocumentSearchGeneral', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='documentsearchgeneral',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='documentsearchgeneral',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='documentsearchbootstrapproperties',
            name='parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.DocumentSearchBootstrap', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='documentsearchbootstrap',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='documentsearchbootstrap',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='disclaimertext',
            name='clinical_domain',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=14, to='dbmconfigapp.ClinicalDomain', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='disclaimertext',
            name='cv_general_page',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.ClinicalViewerGeneralPage', null=True),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='disclaimertext',
            unique_together=set([('culture',)]),
        ),
        migrations.AddField(
            model_name='directmessagingacdmpage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='directmessagingacdmpage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='directmessagingacdm',
            name='parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.DirectMessagingAcdmPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='demographysearchfields',
            name='dbm_patient_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, default=None, verbose_name=b'DbMotion Patient Attribute Name', to='via.InitiateMappings', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='demographysearchfields',
            name='pv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVPatientSearchPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dataexportccdadisplaypage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dataexportccdadisplaypage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dataelement',
            name='clinical_domain',
            field=models.ForeignKey(on_delete=models.SET_NULL, to='dbmconfigapp.ClinicalDomain', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dataelement',
            name='pl_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, to='dbmconfigapp.PlPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dataelement',
            name='pv_parent_patient_display',
            field=models.ForeignKey(on_delete=models.SET_NULL, editable=False, to='dbmconfigapp.PVPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dataaccessauditingpage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dataaccessauditingpage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dataaccessauditing',
            name='parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.DataAccessAuditingPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cvreportingpage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cvreportingpage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cvpatientdisplaypage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cvpatientdisplaypage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cvccdadisplaypage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cvccdadisplaypage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='currentculture',
            name='agenthub_general_page',
            field=models.ForeignKey(on_delete=models.CASCADE, default=1, editable=False, to='dbmconfigapp.AgentHubGeneralPage'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='currentculture',
            name='name',
            field=models.ForeignKey(on_delete=models.CASCADE, verbose_name=b'Select culture', to='dbmconfigapp.Culture', help_text=b'This is the grey text'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='culture',
            name='agenthub_general_page',
            field=models.ForeignKey(on_delete=models.CASCADE, default=1, editable=False, to='dbmconfigapp.AgentHubGeneralPage'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='collaboratepatientsearchproperties',
            name='parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=14, to='dbmconfigapp.PatientSearchPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='collaboratepatientsearchproperties',
            name='pv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVPatientSearchPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='clinicalviewergeneralpage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='clinicalviewergeneralpage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='clinicalviewergeneral',
            name='parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.ClinicalViewerGeneralPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='clinicaldomainproperties',
            name='clinical_domain',
            field=models.ForeignKey(on_delete=models.SET_NULL, to='dbmconfigapp.ClinicalDomain', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='clinicaldomainproperties',
            name='pl_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, to='dbmconfigapp.PlPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='clinicaldomainproperties',
            name='pv_ClinicalDocument_ShowExternalDocumentsLabel',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=None, editable=False, to='dbmconfigapp.PVClinicalDomainPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='clinicaldomainproperties',
            name='pv_parent_patient_display',
            field=models.ForeignKey(on_delete=models.SET_NULL, editable=False, to='dbmconfigapp.PVPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='clinicaldomain',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='clinicaldomain',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='clinicalcodedisplaypage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='clinicalcodedisplaypage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='clinicalcodedisplay',
            name='cv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.ClinicalCodeDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='clinicalcodedisplay',
            name='pl_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PlClinicalCodeDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='clinicalcodedisplay',
            name='pv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=None, editable=False, to='dbmconfigapp.PVClinicalCodeDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='changeshistory',
            name='ccenter_user',
            field=models.ForeignKey(on_delete=models.SET_NULL, to='authccenter.CCenterUser', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ccdadisplay',
            name='cv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.CVCCDADisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ccdadisplay',
            name='dataexport_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.DataExportCCDADisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ccdadisplay',
            name='pv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVCCDADisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='carequalityintegrationsettingspage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='carequalityintegrationsettingspage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='carequalityintegrationsettingsmodel',
            name='page',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.CarequalityIntegrationSettingsPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='capsuleservice',
            name='capsule_page',
            field=models.ForeignKey(on_delete=models.CASCADE, to='dbmconfigapp.CapsulePage'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='capsulepage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='capsulepage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cagdataaccessauditingpage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cagdataaccessauditingpage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cagdataaccessauditing',
            name='parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.CAGDataAccessAuditingPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appsreporting',
            name='cv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.CVReportingPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appsreporting',
            name='reporting_pl',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PlReportingPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appsreporting',
            name='reporting_pv',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVReportingPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appspatientdisplaywithagent',
            name='cv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.CvPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appspatientdisplaywithagent',
            name='pl_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PlPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appspatientdisplaywithagent',
            name='pv_parent_patient_display',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appspatientdisplayvbp',
            name='cv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.CvPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appspatientdisplayvbp',
            name='pl_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PlPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appspatientdisplayvbp',
            name='pv_parent_patient_display',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appspatientdisplayvaluebaseprogram',
            name='cv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.CvPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appspatientdisplayvaluebaseprogram',
            name='pl_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PlPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appspatientdisplayvaluebaseprogram',
            name='pv_parent_patient_display',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appspatientdisplaymetriccodebasedindicator',
            name='pv_parent_patient_display',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='appspatientdisplaymetriccodebasedindicator',
            unique_together=set([('mci_oid_system', 'mci_interpretation')]),
        ),
        migrations.AddField(
            model_name='appspatientdisplaycommon',
            name='cv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.CvPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appspatientdisplaycommon',
            name='pl_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PlPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appspatientdisplayagecalculation',
            name='cv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.CvPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appspatientdisplayagecalculation',
            name='pl_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PlPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appspatientdisplayagecalculation',
            name='pv_parent_patient_display',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appspatientdisplay',
            name='cv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.CvPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appspatientdisplay',
            name='pl_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PlPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appspatientdisplay',
            name='pv_parent_patient_display',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appsadvancedirectivenodes',
            name='cv_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.CvPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appsadvancedirectivenodes',
            name='pl_parent',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PlPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appsadvancedirectivenodes',
            name='pv_parent_patient_display',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.PVPatientDisplayPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='agentusercentricapp',
            name='agentpp_hosted_app_page',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.AgentppHostedAppPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='agentsmartonfhirapp',
            name='agentpp_hosted_app_page',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.AgentppHostedAppPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='agentpphostedapppage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='agentpphostedapppage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='agentpphostedapp',
            name='agentpp_hosted_app_page',
            field=models.ForeignKey(on_delete=models.SET_NULL, default=1, editable=False, to='dbmconfigapp.AgentppHostedAppPage', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='agenthubgeneralpage',
            name='components',
            field=models.ManyToManyField(to='dbmconfigapp.Component', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='agenthubgeneralpage',
            name='services',
            field=models.ManyToManyField(to='dbmconfigapp.Service', null=True),
            preserve_default=True,
        ),
    ]
